CC=g++
CFLAGS=-c -Wall -std=c++14 -lpthread
DEBUG=-O(3) -g(0)

all: runFile

runFile: mandelbrot.o time.o
	$(CC) mandelbrot.o time.o -o execFile

mandelbrot.o: ThreadedMandel.cpp
	$(CC) $(CFLAGS) $(DEBUG) ThreadedMandel.cpp

time.o: Time.cpp
	$(CC) $(CFLAGS) $(DEBUG) Time.cpp

clean:
	rm -rf *o execFile

tar:
	tar zcvf homework02.tar ThreadedMandel.cpp Time.cpp